In [13]:
# We first read the french movies "entrées"
from lib.preprocessing.load import read_movies_entrees, read_movies_features
bo = read_movies_entrees('data/french-box-office-29nov2020.json')

# Then fetch their main features. Note that it seems not all movies were found in the feature database
features = read_movies_features('data/movie-features-29nov2020.json')

# Let's merge both dataframes
import pandas as pd
data = pd.merge(bo, features, on='id')
data

,year,title,id,sales,release_date,is_adult,is_part_of_collection,budget,genres,original_language,production_countries,languages,runtime
0,2019,Maléfique : Le Pouvoir du Mal,19073,786485,2019-10-16,False,True,185000000,"[Fantastique, Familial, Aventure]",en,[US],[en],110.0
1,2019,Nous finirons ensemble,18875,1261701,2019-05-01,False,True,0,"[Comédie, Drame]",fr,"[BE, FR]",[fr],135.0
2,2019,Spider-Man: Far from Home,18243,1370178,2019-07-03,False,True,160000000,"[Action, Aventure, Science-Fiction]",en,[US],"[cs, nl, en, de, it]",129.0
3,2019,Jumanji: next level,18258,785636,2019-12-04,False,True,125000000,"[Aventure, Comédie, Fantastique]",en,[US],[en],123.0
4,2019,Dragons 3 : Le monde caché,18167,1224811,2019-02-06,False,True,129000000,"[Animation, Familial, Aventure]",en,"[JP, US]",[en],104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7048,2017,La Planète des Singes - Suprématie,15748,1016520,2017-08-02,False,True,150000000,"[Drame, Science-Fiction, Guerre]",en,"[CA, US, NZ]",[en],142.0
7049,2017,Cars 3,16452,950353,2017-08-02,False,True,175000000,"[Aventure, Animation, Comédie, Familial]",en,[US],[en],109.0
7050,2017,Le Sens de la fête,17386,808544,2017-10-04,False,False,17200000,[Comédie],fr,[FR],[fr],117.0
7051,2017,Cinquante nuances plus sombres,15186,1618110,2017-02-08,False,True,55000000,"[Drame, Romance]",en,[US],[en],118.0
7052,2017,Patients,16903,309303,2017-03-01,False,False,0,"[Drame, Comédie]",fr,[FR],[fr],110.0

In [14]:
# We first use little house keeping following what we learned in the last notebook

# Remove movies with zero sales
data = data[data["sales"] != 0]

# Remove is_adult variable
data = data.drop(["is_adult"], axis=1, inplace=False)

# For the moment we remove the title columns as well, as we don't know how to process nlp stuff
data = data.drop(["title"], axis=1, inplace=False)

# We remove also complex data => languages and countries of production
data = data.drop(["languages", "production_countries", "year"], axis=1, inplace=False)

# No need of ids anymore
data = data.drop(["id"], axis=1, inplace=False)

In [15]:
# Now let's properly encode our variables
from lib.preprocessing.encode import dummy_encode

data = dummy_encode(
    data, 
    'original_language',
    'original_language_is',
    'fr'
)

In [16]:
from lib.preprocessing.encode import multilabel_encode

data = multilabel_encode(
    data=data, 
    column_to_encode='genres',
    column_to_drop='Action')

In [17]:
data

,sales,release_date,is_part_of_collection,budget,runtime,original_language_is_aa,original_language_is_ab,original_language_is_af,original_language_is_ar,original_language_is_bm,...,Guerre,Histoire,Horreur,Musique,Mystère,Romance,Science-Fiction,Thriller,Téléfilm,Western
0,786485,2019-10-16,True,185000000,110.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1261701,2019-05-01,True,0,135.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1370178,2019-07-03,True,160000000,129.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,785636,2019-12-04,True,125000000,123.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1224811,2019-02-06,True,129000000,104.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7048,1016520,2017-08-02,True,150000000,142.0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
7049,950353,2017-08-02,True,175000000,109.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7050,808544,2017-10-04,False,17200000,117.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7051,1618110,2017-02-08,True,55000000,118.0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
7052,309303,2017-03-01,False,0,110.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
# For the moment we drop rows with nans but we should properly handle these values
data = data.dropna(inplace=False)
data # We removed 40 rows

,sales,release_date,is_part_of_collection,budget,runtime,original_language_is_aa,original_language_is_ab,original_language_is_af,original_language_is_ar,original_language_is_bm,...,Guerre,Histoire,Horreur,Musique,Mystère,Romance,Science-Fiction,Thriller,Téléfilm,Western
0,786485,2019-10-16,True,185000000,110.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1261701,2019-05-01,True,0,135.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1370178,2019-07-03,True,160000000,129.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,785636,2019-12-04,True,125000000,123.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1224811,2019-02-06,True,129000000,104.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7048,1016520,2017-08-02,True,150000000,142.0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
7049,950353,2017-08-02,True,175000000,109.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7050,808544,2017-10-04,False,17200000,117.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7051,1618110,2017-02-08,True,55000000,118.0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
7052,309303,2017-03-01,False,0,110.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
# Let's prepare our data into exog, endo data
data = data.sort_values(by='release_date', inplace=False)

# Features
import statsmodels.api as sm
data_exog = data.copy()
data_exog = data_exog.drop(['sales', 'release_date'], axis=1)
data_exog = sm.add_constant(data_exog, prepend=True)
data_exog = data_exog.astype(float)

# Target
data_endo = data['sales'].copy()
data_endo = data_endo.astype(float)

In [20]:
data

,sales,release_date,is_part_of_collection,budget,runtime,original_language_is_aa,original_language_is_ab,original_language_is_af,original_language_is_ar,original_language_is_bm,...,Guerre,Histoire,Horreur,Musique,Mystère,Romance,Science-Fiction,Thriller,Téléfilm,Western
4802,139087,2000-01-01,False,0,120.0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3144,66228,2000-01-05,False,22000000,142.0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
3139,32954,2000-01-05,False,0,116.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6271,1463152,2000-01-05,False,0,77.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2301,25224,2000-01-12,False,9000000,165.0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,15304,2020-10-07,False,0,60.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
450,25924,2020-10-07,False,0,93.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
453,30218,2020-10-07,False,0,107.0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
466,11185,2020-10-14,False,0,52.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
475,4297,2020-10-21,False,0,126.0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [21]:
# Let's split our dataset into a train / test using released dates
import numpy as np

# Split
X_train, X_test = np.split(data_exog, [int(.8 * len(data_exog))])
y_train, y_test = np.split(data_endo, [int(.8 * len(data_endo))])

In [22]:
# Fit models
import numpy as np
from sklearn import tree
from sklearn.ensemble import RandomForestRegressor

mod = sm.OLS(y_train, X_train)
res = mod.fit()

models = {
    "Linear Regression": sm.OLS(y_train, X_train).fit(),
    "Decision Tree": tree.DecisionTreeRegressor().fit(X_train, y_train),
    "Random Forest": RandomForestRegressor(random_state=1, n_estimators=50).fit(X_train, y_train)
}

for model_name, model in models.items():
    preds = model.predict(X_test)
    fa = round((1 - np.sum(np.abs(y_test - preds))/np.sum(y_test)) * 100, 2)
    
    print()
    print(model_name)
    print(fa)

Linear Regression
19.98

Decision Tree
0.43

Random Forest
12.23

In [23]:
# Interpreting linear regression coefs => 
#   - Being part of collection as a strong impact on sales
#   - Budget as well, positive impact + significant
#   - Runtime as a positive impact
#   - Among original languages, mostly European languages have a significant impact (negative compared to if movie was written in French)
#   - Some genres make a difference compared to Action (Horror => reduces sales, Aventure increases them...)
print(models['Linear Regression'].summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.380
Model:                            OLS   Adj. R-squared:                  0.373
Method:                 Least Squares   F-statistic:                     49.34
Date:                Sun, 13 Dec 2020   Prob (F-statistic):               0.00
Time:                        19:23:55   Log-Likelihood:                -76072.
No. Observations:                5456   AIC:                         1.523e+05
Df Residuals:                    5388   BIC:                         1.527e+05
Df Model:                          67
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                     1.44e+05   1.91e+04      7.543      0.000    1.07e+05    1.81e+05
is_part_of_collection    2.277e+05   1.25e+04     18.282      0.000    2.03e+05    2.52e+05
budget                      0.0044      0.000     32.145      0.000       0.004       0.005
runtime                   460.6517    181.574      2.537      0.011     104.693     816.610
original_language_is_aa -1.895e+05   2.77e+05     -0.683      0.495   -7.33e+05    3.54e+05
original_language_is_ab -1.356e+05   2.77e+05     -0.489      0.625   -6.79e+05    4.08e+05
original_language_is_af -4.079e+04   2.77e+05     -0.147      0.883   -5.84e+05    5.02e+05
original_language_is_ar -1.301e+05   8.03e+04     -1.620      0.105   -2.88e+05    2.74e+04
original_language_is_bm -1.406e+05   1.96e+05     -0.718      0.473   -5.24e+05    2.43e+05
original_language_is_bn  1.229e-05      0.000      0.026      0.979      -0.001       0.001
original_language_is_bs  -1.18e+05   2.77e+05     -0.426      0.670    -6.6e+05    4.24e+05
original_language_is_ca -1.768e+05   2.77e+05     -0.638      0.523    -7.2e+05    3.66e+05
original_language_is_cn -1.705e+05   1.05e+05     -1.624      0.104   -3.76e+05    3.53e+04
original_language_is_cs -1.835e+05   1.39e+05     -1.320      0.187   -4.56e+05     8.9e+04
original_language_is_da -1.693e+05   7.19e+04     -2.354      0.019    -3.1e+05   -2.83e+04
original_language_is_de -1.403e+05   3.62e+04     -3.872      0.000   -2.11e+05   -6.93e+04
original_language_is_el -1.544e+05   1.96e+05     -0.788      0.430   -5.38e+05    2.29e+05
original_language_is_en -1.431e+05   9254.801    -15.462      0.000   -1.61e+05   -1.25e+05
original_language_is_es -1.154e+05   2.56e+04     -4.508      0.000   -1.66e+05   -6.52e+04
original_language_is_et -1.471e+05   2.78e+05     -0.529      0.597   -6.93e+05    3.98e+05
original_language_is_fa -1.072e+05   8.39e+04     -1.278      0.201   -2.72e+05    5.72e+04
original_language_is_fi -1.396e+05   1.05e+05     -1.328      0.184   -3.46e+05    6.64e+04
original_language_is_he  -1.52e+05   6.97e+04     -2.179      0.029   -2.89e+05   -1.53e+04
original_language_is_hi -1.776e+05   6.13e+04     -2.899      0.004   -2.98e+05   -5.75e+04
original_language_is_hu -1.281e+05    1.6e+05     -0.800      0.424   -4.42e+05    1.86e+05
original_language_is_hz     0.0004      0.015      0.026      0.979      -0.029       0.029
original_language_is_id  -3.63e+05   1.97e+05     -1.846      0.065   -7.49e+05    2.26e+04
original_language_is_is -1.335e+05   1.96e+05     -0.682      0.495   -5.17e+05     2.5e+05
original_language_is_it -1.481e+05   3.12e+04     -4.742      0.000   -2.09e+05   -8.69e+04
original_language_is_ja  -2.01e+05   3.59e+04     -5.604      0.000   -2.71e+05   -1.31e+05
original_language_is_ka -1.497e+05   1.96e+05     -0.763      0.446   -5.34e+05    2.35e+05
original_language_is_ko -1.439e+05   5.59e+04     -2.573      0.010   -2.54e+05   -3.42e+04
original_language_is_ku -1.052e+05   2.77e+05     -0.380      0.704   -6.48e+05    4.37e+05
original_language_is_mk     0.0018      0.068      0.026      0.979      -0.132       0.136
original_language_is_mn -8.561e+04   1.96e+05     -0.437      0.662    -4.7e+05    2.98e+05
original_language_is_nl -1.361e+05   8.78e+04     -1.549      0.121   -3.08e+05    3.61e+04
original_language_is_no -1.635e+05   1.13e+05     -1.444      0.149   -3.85e+05    5.85e+04
original_language_is_pl -1.204e+05   1.24e+05     -0.970      0.332   -3.64e+05    1.23e+05
original_language_is_ps -9.739e+04   2.77e+05     -0.352      0.725    -6.4e+05    4.45e+05
original_language_is_pt -1.607e+05   5.49e+04     -2.927      0.003   -2.68e+05   -5.31e+04
original_language_is_ro -1.342e+05   1.39e+05     -0.968      0.333   -4.06e+05    1.38e+05
original_language_is_ru -7.874e+04   9.81e+04     -0.802      0.422   -2.71e+05    1.14e+05
original_language_is_sk    -0.0003      0.011     -0.026      0.979      -0.022       0.021
original_language_is_sr  -1.45e+05   1.96e+05     -0.740      0.460   -5.29e+05    2.39e+05
original_language_is_sv  -2.31e+05   8.06e+04     -2.866      0.004   -3.89e+05    -7.3e+04
original_language_is_ta -2.215e+05   1.96e+05     -1.129      0.259   -6.06e+05    1.63e+05
original_language_is_te -5.177e+05   2.77e+05     -1.868      0.062   -1.06e+06    2.56e+04
original_language_is_th -1.649e+05   1.39e+05     -1.188      0.235   -4.37e+05    1.07e+05
original_language_is_tl -1.142e+05   1.96e+05     -0.582      0.561   -4.99e+05    2.71e+05
original_language_is_tr -1.136e+05   1.05e+05     -1.084      0.279   -3.19e+05    9.19e+04
original_language_is_vi -1.309e+05   1.96e+05     -0.669      0.504   -5.15e+05    2.53e+05
original_language_is_xh -1.302e+05   2.77e+05     -0.471      0.638   -6.73e+05    4.12e+05
original_language_is_xx -1.136e+05   1.39e+05     -0.818      0.413   -3.86e+05    1.59e+05
original_language_is_yi     0.0009      0.035      0.026      0.979      -0.067       0.069
original_language_is_zh -1.483e+05   5.12e+04     -2.897      0.004   -2.49e+05   -4.79e+04
Animation                1.716e+04   1.92e+04      0.895      0.371   -2.04e+04    5.47e+04
Aventure                 5.331e+04   1.46e+04      3.640      0.000    2.46e+04     8.2e+04
Comédie                  9813.2862   9234.830      1.063      0.288   -8290.714    2.79e+04
Crime                    2956.9087   1.33e+04      0.222      0.824   -2.31e+04    2.91e+04
Documentaire            -6970.1485   1.96e+04     -0.356      0.722   -4.53e+04    3.14e+04
Drame                   -3.666e+04   9405.782     -3.897      0.000   -5.51e+04   -1.82e+04
Familial                -9.065e+04   1.74e+04     -5.207      0.000   -1.25e+05   -5.65e+04
Fantastique              3.869e+04   1.57e+04      2.465      0.014    7921.885    6.95e+04
Guerre                  -7460.2297   2.73e+04     -0.273      0.785    -6.1e+04    4.61e+04
Histoire                -1.334e+04   2.11e+04     -0.633      0.526   -5.46e+04    2.79e+04
Horreur                 -5.283e+04   1.77e+04     -2.982      0.003   -8.76e+04   -1.81e+04
Musique                  1.586e+04   2.49e+04      0.636      0.525    -3.3e+04    6.48e+04
Mystère                  2.578e+04    1.7e+04      1.515      0.130   -7570.866    5.91e+04
Romance                  1.073e+04   1.09e+04      0.985      0.324   -1.06e+04    3.21e+04
Science-Fiction         -2.577e+04   1.75e+04     -1.476      0.140      -6e+04    8458.967
Thriller                -1.178e+04   1.18e+04     -1.002      0.316   -3.48e+04    1.13e+04
Téléfilm                 2.095e+04   4.04e+04      0.519      0.604   -5.82e+04       1e+05
Western                 -2.403e+04   4.34e+04     -0.554      0.580   -1.09e+05     6.1e+04
==============================================================================
Omnibus:                     4855.744   Durbin-Watson:                   2.037
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           276251.363
Skew:                           4.038   Prob(JB):                         0.00
Kurtosis:                      36.911   Cond. No.                     1.19e+24
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.18e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.